print("Hola Mundo")
hola="hola mundo"
print(hola.upper())
print(hola.lower())
print(hola.capitalize())
print(hola.replace('mundo','broo'))
print(hola.count('o'))
print(hola.startswith('h'))
print(hola.endswith('do'))
print(hola.split())
print(hola.find('h'))
print(len(hola))
print(hola.index('o'))
print(hola.isnumeric())
print(hola.isalpha())

print(hola[3])